# https://docs.qmk.fm/

KEYBOARD_SHARED_EP = yes

JOYSTICK_ENABLE = yes
JOYSTICK_DRIVER = analog

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

RGB_MATRIX_SUPPORTED = yes
RGBLIGHT_SUPPORTED = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = pwm
